### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by joshhamon** [artmih24/TeleParser#3]
After getting going and downloading the dependencies, I am getting an error around bot users. See below.  

`Traceback (most recent call last):
  File "/Users/johamon/TeleParser/TeleParser.py", line 128, in <module>
    client.loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/johamon/TeleParser/TeleParser.py", line 111, in main
    await dump_all_messages(channel, channel_string, datetime_string)
  File "/Users/johamon/TeleParser/TeleParser.py", line 88, in dump_all_messages
    history = await client(GetHistoryRequest(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetHistoryRequest)`

**Comment by Danil-Gromakov** [comment]
Hi, [joshhamon](https://github.com/joshhamon)

I used this code today successfully, and collect messages from a telegram chat by TeleParser. 

The error says: The API access **for bot users** is restricted. The method you tried to invoke **cannot be executed as a bot** (caused by GetHistoryRequest)

You can try create new api_id and api_hash for telegram app

The docs https://core.telegram.org/api/obtaining_api_id

If it not work, ask me I help you.
